<<<<<<< HEAD
<<<<<<< HEAD
//Interface
interface A
{
	int a = 12;
	public static void main(String[] args) 
	{
		System.out.println("Hello generated by Interface");
	}
}
abstract class B 
{
	int b = 22;
	abstract void display();
	public static void main(String[] args) 
	{
		System.out.println("hello generated by Abstract class");
	}
}
enum C 
{;
	public static void main(String[] args) 
	{
		System.out.println("Hello generated by enum");
	}
}
class Test
{
	public static void main(String[] args) 
	{
		System.out.println("Hello generated by Complete class");

		//new A();		//Error
		//new B();		//Error
	}
=======
//Interface
interface A
{
	int a = 12;
	public static void main(String[] args) 
	{
		System.out.println("Hello generated by Interface");
	}
}
abstract class B 
{
	int b = 22;
	abstract void display();
	public static void main(String[] args) 
	{
		System.out.println("hello generated by Abstract class");
	}
}
enum C 
{;
	public static void main(String[] args) 
	{
		System.out.println("Hello generated by enum");
	}
}
class Test
{
	public static void main(String[] args) 
	{
		System.out.println("Hello generated by Complete class");

		//new A();		//Error
		//new B();		//Error
	}
>>>>>>> db80c5c9e978e8d9089e4f7e7e0501a2ee2f811a
=======
//Interface
interface A
{
	int a = 12;
	public static void main(String[] args) 
	{
		System.out.println("Hello generated by Interface");
	}
}
abstract class B 
{
	int b = 22;
	abstract void display();
	public static void main(String[] args) 
	{
		System.out.println("hello generated by Abstract class");
	}
}
enum C 
{;
	public static void main(String[] args) 
	{
		System.out.println("Hello generated by enum");
	}
}
class Test
{
	public static void main(String[] args) 
	{
		System.out.println("Hello generated by Complete class");

		//new A();		//Error
		//new B();		//Error
	}
>>>>>>> db80c5c9e978e8d9089e4f7e7e0501a2ee2f811a
}